# SPDX-License-Identifier: GPL-2.0-or-later
if(NOT DEFINED OPENXHCCTL OR NOT DEFINED OPENXHCCTL_FAULT_TEST OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED TEST_WORK_DIR)
  message(FATAL_ERROR "CLI test configuration is incomplete")
endif()

file(MAKE_DIRECTORY "${TEST_WORK_DIR}")
set(imported_trace "${TEST_WORK_DIR}/imported.xhctrace")
set(bad_header "${TEST_WORK_DIR}/bad-header.xhctrace")
set(bad_native_record "${TEST_WORK_DIR}/bad-native-record.xhctrace")
set(bad_tshark_record "${TEST_WORK_DIR}/bad-tshark-record.tsv")
set(unwritable_output "${TEST_WORK_DIR}/output-directory")
set(same_path "${TEST_WORK_DIR}/same-path.tsv")
set(same_path_contents "0.000001000\t0x81\t04:00:01:02\n")
set(protected_parent "${TEST_WORK_DIR}/protected-parent")
set(sentinel_output "${protected_parent}/sentinel.xhctrace")
set(sentinel_contents "DO_NOT_REPLACE\n")
file(MAKE_DIRECTORY "${unwritable_output}")
file(WRITE "${bad_header}" "NOT_OPENXHC_TRACE_V1\n1000\tIN\t04000102\n")
file(WRITE "${bad_native_record}" "OPENXHC_TRACE_V1\n1000\tIN\t04000102\n\n2000\tSIDE\t04\n")
file(WRITE "${bad_tshark_record}" "0.000001000\t0x81\t04:00:01:02\n\n0.000002000\t0x83\t0b\n")
file(WRITE "${same_path}" "${same_path_contents}")

function(expect_exit expected expected_stdout expected_stderr name)
  execute_process(
    COMMAND "${OPENXHCCTL}" ${ARGN}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error)
  if(NOT result EQUAL expected)
    message(FATAL_ERROR "${name}: expected exit ${expected}, got ${result}")
  endif()
  if(expected_stdout STREQUAL "empty" AND NOT output STREQUAL "")
    message(FATAL_ERROR "${name}: stdout must be empty")
  endif()
  if(expected_stdout STREQUAL "nonempty" AND output STREQUAL "")
    message(FATAL_ERROR "${name}: stdout must be nonempty")
  endif()
  if(expected_stderr STREQUAL "empty" AND NOT error STREQUAL "")
    message(FATAL_ERROR "${name}: stderr must be empty")
  endif()
  if(expected_stderr STREQUAL "nonempty" AND error STREQUAL "")
    message(FATAL_ERROR "${name}: stderr must be nonempty")
  endif()
  set(LAST_OUTPUT "${output}" PARENT_SCOPE)
  set(LAST_ERROR "${error}" PARENT_SCOPE)
endfunction()

function(expect_fixture_exit expected expected_stdout expected_stderr name)
  execute_process(
    COMMAND "${OPENXHCCTL_FAULT_TEST}" ${ARGN}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error)
  if(NOT result EQUAL expected)
    message(FATAL_ERROR "${name}: expected exit ${expected}, got ${result}")
  endif()
  if(expected_stdout STREQUAL "empty" AND NOT output STREQUAL "")
    message(FATAL_ERROR "${name}: stdout must be empty")
  endif()
  if(expected_stdout STREQUAL "nonempty" AND output STREQUAL "")
    message(FATAL_ERROR "${name}: stdout must be nonempty")
  endif()
  if(expected_stderr STREQUAL "empty" AND NOT error STREQUAL "")
    message(FATAL_ERROR "${name}: stderr must be empty")
  endif()
  if(expected_stderr STREQUAL "nonempty" AND error STREQUAL "")
    message(FATAL_ERROR "${name}: stderr must be nonempty")
  endif()
  set(LAST_FIXTURE_OUTPUT "${output}" PARENT_SCOPE)
endfunction()

expect_fixture_exit(0 nonempty empty device_list_redacted device list)
string(REGEX MATCHALL "path=<redacted>" redacted_paths "${LAST_FIXTURE_OUTPUT}")
list(LENGTH redacted_paths redacted_path_count)
if(NOT redacted_path_count EQUAL 2)
  message(FATAL_ERROR "device_list_redacted: expected two redacted paths")
endif()
string(FIND "${LAST_FIXTURE_OUTPUT}" "/dev/hidraw-fixture" leaked_path)
if(NOT leaked_path EQUAL -1)
  message(FATAL_ERROR "device_list_redacted: raw HID path leaked")
endif()
foreach(expected "10ce:eb73" "interface=0" "interface=1" "product=\"XHC MACH3 CARD\"" "release=0x0100")
  string(FIND "${LAST_FIXTURE_OUTPUT}" "${expected}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "device_list_redacted: missing expected identity field")
  endif()
endforeach()

expect_fixture_exit(0 nonempty empty device_list_show_paths device list --show-paths)
foreach(expected "/dev/hidraw-fixture-0" "/dev/hidraw-fixture-1")
  string(FIND "${LAST_FIXTURE_OUTPUT}" "${expected}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "device_list_show_paths: missing requested local path")
  endif()
endforeach()
string(FIND "${LAST_FIXTURE_OUTPUT}" "path=<redacted>" unexpected_redaction)
if(NOT unexpected_redaction EQUAL -1)
  message(FATAL_ERROR "device_list_show_paths: paths remained redacted")
endif()

if(NOT OPENXHC_ENABLE_HIDAPI)
  expect_exit(5 empty nonempty device_list_hidapi_off device list)
  string(FIND "${LAST_ERROR}" "OpenXHC was built without HIDAPI" hidapi_off_diagnostic)
  if(hidapi_off_diagnostic EQUAL -1)
    message(FATAL_ERROR "device_list_hidapi_off: missing exact HIDAPI-off diagnostic")
  endif()
  expect_exit(5 empty nonempty device_list_show_paths_hidapi_off device list --show-paths)
endif()
expect_exit(2 empty nonempty device_list_unknown_option device list --show-path)
expect_exit(2 empty nonempty device_list_extra_argument device list --show-paths extra)

expect_exit(0 empty empty validate_fixture trace validate "${FIXTURE_DIR}/baseline.xhctrace")
expect_exit(0 nonempty empty summary_fixture trace summary "${FIXTURE_DIR}/baseline.xhctrace")
foreach(expected "records=3" "in=2" "out=1" "report_id[0x04]=2")
  string(FIND "${LAST_OUTPUT}" "${expected}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "summary_fixture: missing expected synthetic count")
  endif()
endforeach()

expect_exit(0 empty empty import_fixture trace import-tshark "${FIXTURE_DIR}/tshark-baseline.tsv" "${imported_trace}")
if(NOT EXISTS "${imported_trace}")
  message(FATAL_ERROR "import_fixture: output file was not created")
endif()
file(READ "${imported_trace}" imported_contents)
set(expected_imported "OPENXHC_TRACE_V1\n1000\tIN\t04000102\n2000\tOUT\t0b000000\n")
if(NOT imported_contents STREQUAL expected_imported)
  message(FATAL_ERROR "import_fixture: output is not canonical")
endif()
expect_exit(0 empty empty validate_imported trace validate "${imported_trace}")
expect_exit(0 nonempty empty summary_imported trace summary "${imported_trace}")

expect_exit(2 empty nonempty missing_syntax trace)
expect_exit(2 empty nonempty missing_validate_input trace validate)
expect_exit(2 empty nonempty extra_validate_argument trace validate "${FIXTURE_DIR}/baseline.xhctrace" extra)
expect_exit(2 empty nonempty unknown_command trace unknown "${FIXTURE_DIR}/baseline.xhctrace")
expect_exit(2 empty nonempty missing_import_output trace import-tshark "${FIXTURE_DIR}/tshark-baseline.tsv")

expect_exit(3 empty nonempty missing_native_input trace validate "${TEST_WORK_DIR}/missing.xhctrace")
expect_exit(3 empty nonempty missing_tshark_input trace import-tshark "${TEST_WORK_DIR}/missing.tsv" "${imported_trace}")
expect_exit(3 empty nonempty unwritable_import_output trace import-tshark "${FIXTURE_DIR}/tshark-baseline.tsv" "${unwritable_output}")
expect_exit(3 empty nonempty same_input_output trace import-tshark "${same_path}" "${same_path}")
file(READ "${same_path}" same_path_after)
if(NOT same_path_after STREQUAL same_path_contents)
  message(FATAL_ERROR "same_input_output: source was modified")
endif()

expect_exit(4 empty nonempty invalid_header trace validate "${bad_header}")
expect_exit(4 empty nonempty invalid_native_record trace validate "${bad_native_record}")
expect_exit(4 empty nonempty invalid_tshark_record trace import-tshark "${bad_tshark_record}" "${imported_trace}")

file(MAKE_DIRECTORY "${protected_parent}")
file(WRITE "${sentinel_output}" "${sentinel_contents}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env OPENXHCCTL_TEST_FAIL_STAGING=1 "${OPENXHCCTL_FAULT_TEST}" trace import-tshark "${FIXTURE_DIR}/tshark-baseline.tsv" "${sentinel_output}"
  RESULT_VARIABLE preservation_result
  OUTPUT_VARIABLE preservation_stdout
  ERROR_VARIABLE preservation_stderr)
file(READ "${sentinel_output}" preserved_contents)
file(GLOB protected_artifacts "${protected_parent}/*" "${protected_parent}/.*.openxhcctl-*")
file(REMOVE_RECURSE "${protected_parent}")
if(NOT preservation_result EQUAL 3)
  message(FATAL_ERROR "preserved_destination: expected exit 3, got ${preservation_result}")
endif()
if(NOT preservation_stdout STREQUAL "")
  message(FATAL_ERROR "preserved_destination: stdout must be empty")
endif()
if(preservation_stderr STREQUAL "")
  message(FATAL_ERROR "preserved_destination: stderr must be nonempty")
endif()
string(FIND "${preservation_stderr}" "unable to write trace output" preservation_diagnostic)
if(preservation_diagnostic EQUAL -1)
  message(FATAL_ERROR "preserved_destination: expected staging-write diagnostic")
endif()
if(NOT preserved_contents STREQUAL sentinel_contents)
  message(FATAL_ERROR "preserved_destination: sentinel was modified")
endif()
list(LENGTH protected_artifacts protected_artifact_count)
if(NOT protected_artifact_count EQUAL 1)
  message(FATAL_ERROR "preserved_destination: temporary artifact was not cleaned up")
endif()
